# Generated by Django 5.0 on 2024-01-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('weight', models.IntegerField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='images/')),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.foodtype')),
            ],
        ),
    ]
