# Generated by Django 4.1.6 on 2024-01-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_foodtype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
