# Generated by Django 4.1.6 on 2024-01-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_food_calories_food_description_alter_food_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
